services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=ASIAZI2LIYB4AGUHGVGP
      - AWS_SECRET_ACCESS_KEY=kZ9a1Cks4i0ZyKYAcdKz3G98FNvRc6bzgjci7K/Z
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEAYaCXVzLWVhc3QtMSJHMEUCIE2SM4nb423FjfDvu9jG8Y/TSCXbq3hENv45Ab98KViAAiEAonjYQdol3b9T2SZKQHTeOs9si8JH6AswyGsqrZB9Wr4q5gIIfhAAGgw2Mzc0MjM2MzI1MDQiDM+4tKLr406pqcosGCrDArEAKBuyUWGaj4wUdNqIcioYs1a3ImPtqpznvY0huQJm2fEcyVmMNEKWYGLw4RvYQO2ExbPs3AcKHiH+QOtcrZ31uSudla5OUQWZ0+kT68+D9UA0qXVPxSc4WkXHuRfsYrS4u5tlAyjYNzjGjyRyvww7CXArkR1zapEVmBsBfVuqw4RiSdRUif0/kgO6O/UO+WkxsnLdLO2p6VEpjRcP5Z7emOaCi+GhndwqOPgiKqilpYacwJIHwIKMOFqulPNa8reWSj1SjEE8YYujkTr0bGo2RBoIz1FWnng8npOhGJMiHyvOIoCr9kJRHsZF7Y57PCWnx3rpUipxJKBHdHqt1Zy9Ih57KY9zZ5/Da2LzvthwFiN9tDwKI1v8Uo0yS6qcPQ5/7jqMpSabPFzaVxZyyqd9am1+Qt1q5sv29bI4+RrlCC4TMODGirkGOqcB+0vFT6bwmopI0JZnE//WYMLlJTnI6LPNz+JM0zgABZyXsYcUWa6c+miaHBjTfgqjTpgFagX9ykx1hjM06WqC0XyYm8jgz+sOcveVqQ7gCvqX3V/uDeDQbn3VxOdVtc9Xl4OCLeg8e8lmAlPgUu+irNd0wQwpqQGNc5rvuD5zvx9hhHrk0IdWJeG8ThayVbUjQo6ptoStEA1bqTuXGekWP0ZjdxKGAEw=
      - AWS_DEFAULT_REGION=us-east-1
      - TF_WORKSPACE=
