services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=ASIAZI2LIYB4ERWEVODF
      - AWS_SECRET_ACCESS_KEY=MIEvH5FJ3CwL2CBw7dZv5j/cO6/w/rD7jQunUk4J
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEOj//////////wEaCXVzLWVhc3QtMSJGMEQCIEBcCPDUwqlcIX1Iuohc3ugbBN5u6jwriq6YAGYiunvrAiBlSE0xNhwIcitLIFlbFSZ54XZ5m156NJo0B8kI9At07SrmAghhEAAaDDYzNzQyMzYzMjUwNCIMLMAyVyenqybhqln3KsMCCIAQuh2j1W5nm/OgWK53mT1vITesG9dCtt6jOACQnV0FrIrYkVG8Pqcbf9YdVQ0kwCXeKxB9UbOP6JVEmQG8b9mXykXBQ7wa1y8m9D6uS8L6ssjMjTHhoE4bTjOKUJmPEh0sudffL+stL+TC0Iy7l42qgiyRee3RjHOX/H0wasFry5WBnmHGDGe6jp1ZTYlIC0M8l1FsP/GOyeISc8HioFjyGGVBHeOl260Y/tVMz5oRrDvZ8bHEAApC0xMWBOiYY0xYQfU7p+pPkJDD6muSqytga2BgsT4ZwOTWdbvKRcIi6y3AuJ9C1YbluHvTi20Vk7IzYM7MybgwoPcotBbCo78Q41HYXsyYXQ+S50tOJYSz7r1w0s+i9VHTCCTJihbTQBU/QsThhIlv3+lk1p5H+mS1+ssrxKxSbEECoLul8AROebAw6P2DuQY6qAEQK62gDHZVV4MKEFmbSlfIpwBP/DxA5V1WI2AodUi+ULjxusy97idLOikx8beX42pqee/P/qwtB0ZVA8YCyXRygmoRex8NrpqXNEoSqLzWSxJd8on+9XrQZKykLsM5nipCuP57PArBb6oRvQKvOXKI9BexVdS1I8fe29YfpMjjDtzUYzzz/qT80/AfCO5/+jLfOiLYM+40myax0KYeP/hwc5mJ910Wf/k=
      - AWS_DEFAULT_REGION=us-east-1
      - TF_WORKSPACE=
