services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=ASIAZI2LIYB4CMYNVZEO
      - AWS_SECRET_ACCESS_KEY=+KIjB7JgowFDOmOYiZZlhKZKLf3/Iy0pLlQ37Y6z
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEN3//////////wEaCXVzLWVhc3QtMSJGMEQCIGLH0idOF7+UMfJOBoSTYgntQTKcUoGxnWxWLtG8hHYbAiA3HvRBJxGIA/niJ9SdbWhl/WT9i05dw4Rm27JADLzw0irmAghWEAAaDDYzNzQyMzYzMjUwNCIMhOPSbIAIq5M1o5yXKsMCKr+nWIjbBmDQk6PhHjZ2CjquqZlKBmhRVPeT/RtgOtj1Y9icuzhQEgGOrEa4Bu+4+jo9UCrcF+HeIyPl5Q+dCW0nfYDHc6gkCChKABhohvmxEdtLVwrsad7AEqrIIkfwIN64hHGuyGEaeot1dCijlQ5DxBH0ohV5IpTGsDfyC2zsRV+nx/nRXjA1sNnRlc+ewpcGIxQC/U6EJWwpz3OYBQbNToonYTXPMQcmKckmvoTm8dfUwXGx4k+NqLmNSi0KmVhAjzqZRldHjAzC1sxbeKed183qPs7pth+fZI2M4NSMPfsj/tF2i+k2UrAQlmp6OosMu63glv2tXn8gzjUYaKPn0ichqe7GOTDTf+jysrnfGUa7PcpNEjm96ZmoWxH6xpYYeBESF8tk/xfafF74AFfn4mw31Ql516/O6xswUtn7mcMwtdiBuQY6qAFxFI+IjOpyK3kMz1iKhbDAue3iU9qySNatiZOoukB0BKt7T25mkSbZY1olJ/+ZxQgyuPanLqj9xV/DN0KcRbiV75137wiAPIWEdcmdeEMsTIve1aiOvZ0ONlBQ3DqSYnaQjpkf3KJH9fxwNc25YHTQj2/O7lzZHkkhUd+2XQWNNxw4YvKGqRj5nzJUpbWCALecTcHM+UIWDu3Xv77eBPSt9e0sQtIA78s=
      - AWS_DEFAULT_REGION=us-east-1
      - TF_WORKSPACE=
